export const FIRST_TIMER_FOCUS_MINUTE = 50;
export const FIRST_TIMER_BREAK_MINUTE = 10;

export const SECOND_TIMER_FOCUS_MINUTE = 25;
export const SECOND_TIMER_BREAK_MINUTE = 5;

export const MODIFY_TIME_MINUTE = 5;
